Cargo.lock
bootstrap/state-builder/Cargo.toml
bootstrap/state-builder/src/build_address_utxos.rs
bootstrap/state-builder/src/build_balances.rs

Rather than computing the entire state from scratch by feeding all the blocks to the canister, we'll now rely on Bitcoin's chainstate database. This will allow us to compute the whole state in a matter of hours, as opposed to weeks or months.
This commit introduces two of several scripts that will be used to read data from the chainstate database and compute various parts of the canister's state.

feat: [EXC-1283] script to compute the address balances and UTXOs.

---

dfx.json
e2e-tests/build.sh

Fix building e2e scenarios on macs. Prior to this commit building on macs was possible by first building the bitcoin canister.
Now the build scripts are more robust so that they can compile on a mac under all situations.

fix: fix build scripts for e2e scenarios on mac.

---

bootstrap/state-builder/src/build_address_utxos.rs
bootstrap/state-builder/src/build_balances.rs
bootstrap/state-builder/src/build_utxos.rs

When pre-computing the state we rely on a 3rd party tool that outputs a text dump of the UTXOs. Not all the addresses we support are emitted by this tool, so as a result we don't include all the addresses we support in our state.
This commit fixes this issue by adding a fallback mechanism. If parsing the address fails (e.g. it doesn't exist), we attempt to parse the script of the UTXO directly.

fix: load all supported addresses from the utxo dump file

---

canister/src/types.rs
e2e-tests/profiling/scenario-1.txt
e2e-tests/profiling/scenario-2.txt

Updates the byte representation of the `(TxOut, Height)` type. The motivation behind this change is that we'll add support for encoding tuples in the `stable-structures` crate soon, and this update makes it compatible with the way we'll be encoding tuples there.

chore: update byte representation of `(TxOut, Height)`.

---

canister/src/api/set_config.rs
canister/src/main.rs

We had a hard-coded principal there as a stop-gap measure.

fix: only a canister's controllers can call `set_config`.

---

canister/src/api/send_transaction.rs
canister/src/lib.rs

We'll first be deploying the bitcoin canister with the endpoints disabled. This commit
ensures all the endpoints are disabled until we've synced the canister to the tip.

[Launch Branch] Disable Endpoints

---

canister/src/api/get_utxos.rs
e2e-tests/profiling/scenario-1.txt
e2e-tests/profiling/scenario-2.txt
e2e-tests/scenario-1.sh
e2e-tests/scenario-2.sh

This change is in line with the new pricing we're introducing.

chore: reduce max UTXOs per response to 1k.

---

Cargo.lock
canister/Cargo.toml
canister/src/lib.rs
canister/src/runtime.rs

This PR prettifies cycles in error messages.
Before: `Received 1234567890 cycles. 999234567890 cycles are required.`
After: `Received 1_234_567_890 cycles. 999_234_567_890 cycles are required.`

feat: prettify cycles error message

---

Cargo.lock
canister/Cargo.toml
canister/src/lib.rs

This PR reverts pretty cycles in error message from #119, since it's a breaking change (any canister parsing this message will break), but keeps adding tests.
Before: `Received 1_234_567_890 cycles. 999_234_567_890 cycles are required`.
After: `Received 1234567890 cycles. 999234567890 cycles are required`.

chore: revert pretty cycles in error message

---

bootstrap/main-state-builder/src/main.rs
bootstrap/state-builder/src/build_utxos.rs
bootstrap/state-builder/src/main.rs
canister/candid.did
canister/src/api/send_transaction.rs
canister/src/api/set_config.rs
canister/src/lib.rs
canister/src/state.rs
canister/src/types.rs
e2e-tests/profiling/scenario-1.txt
e2e-tests/profiling/scenario-2.txt
e2e-tests/scenario-1.sh
e2e-tests/scenario-2.sh
e2e-tests/scenario-3.sh

This PR adds a flag that allows us to enable/disable access to the bitcoin apis provided by the canister. The flag is set to have a default value of `true` to not disrupt the current operations of the canister. It's also added in the canister's `Config` so that it can eventually be set through a proposal that triggers the `set_config` endpoint of the canister. For now, if we need to disable the apis, we can set the flag to `Disabled` in the canister's post upgrade hook.

feat: Add a flag to disable bitcoin apis

---

validation/src/constants.rs
validation/src/header.rs
validation/src/lib.rs

Removes two validation checks that are not particularly useful for us.
1. Checking that the header is within one year of tip. The canister already rejects any header/block that doesn't extend the anchor or its successors, so we effectively reject anything that's older than a day already.
2. Checkpoints. We bootstrap the canister using bitcoind, and it starts after all of the encoded checkpoints, so that check doesn't bring value.

chore: remove unneeded block validation checks.

---

validation/src/header.rs

In the block validation code, computing the next difficulty traverses back 2,016 blocks linearly. Given that these code paths will be using stable structures, this is quite wasteful. The interface of `HeaderStore` has been modified to allow fetching a block using its height, so that traversing 2,016 blocks is now done in one single call.

chore: optimize computing next difficulty

---

canister/src/types.rs
validation/src/lib.rs

Computing the block difficulty is needed for computing the difficulty-based stability threshold that will be introduced in an upcoming commit.
We are not relying on the [difficulty](https://docs.rs/bitcoin/latest/bitcoin/blockdata/block/struct.BlockHeader.html#method.difficulty) method in the bitcoin crate, as it produces incorrect results for testnet and regtest.

feat: compute block difficulty

---

e2e-tests/profiling/scenario-1.txt
e2e-tests/profiling/scenario-2.txt

We didn't update the profiling metrics in #126, so this commit updates the profiling metrics.
There's a notable improvement in the `get_balance` and get_utxos` requests (see scenario 2).

chore: update profiling metrics

---

canister/Cargo.toml
dfx.json
e2e-tests/profiling/scenario-1.txt
e2e-tests/profiling/scenario-2.txt
scripts/build-canister.sh

* `build-canister.sh` now gzips all the canisters.
* The `byte_order` dependency is moved as a dev dependecy.
* The canister's binary is renamed to `ic-btc-canister`, which is more consistent with the naming of other canisters.

chore: gzip canisters + minor enhancements

---

canister/src/address_utxoset.rs
canister/src/lib.rs
canister/src/state.rs
canister/src/unstable_blocks.rs
canister/src/utxo_set.rs

After the latest release, the `network` field in `UnstableBlocks` no longer needs to be optional.
Closes [EXC-1310](https://dfinity.atlassian.net/browse/EXC-1310).

chore: make the network field in `UnstableBlocks` non-optional

---

canister/src/lib.rs

Closes EXC-1322.
Problem:
The init method currently ignores the syncing flag. When the canister starts, its syncing flag will always be enabled even if syncing is set to disabled in the init parameters.
Solution:
To fix this, the init method needs to update the syncing flag based on the given config.

fix: Set syncing flag in init method.

---

Cargo.lock
canister/Cargo.toml
canister/src/api/metrics.rs
canister/src/metrics.rs
canister/src/state.rs
canister/src/utxo_set.rs
e2e-tests/profiling/scenario-1.txt
e2e-tests/profiling/scenario-2.txt

Problem:
We currently do not have a way of tracking how many instructions it takes to ingest new Bitcoin blocks.
Solution:
Keep track of the latest stats in a variable and expose them as a metric so that we can track these on our dashboards.

feat: Add metric to track block ingestion instruction counts

---

canister/src/api/fee_percentiles.rs

Problem:
When computing the fee percentiles for the last N transactions, coinbase transactions were counted as part of N. In practice, the difference is negligible, but for the sake of correctness, coinbase transactions shouldn't be counted at all.
Solution:
Do not increment the transaction count when encounterting coinbase transactions.

fix: ignore coinbase transactions when computing fee percentiles.

---

canister/src/api/metrics.rs
canister/src/metrics.rs
canister/src/state.rs

Inserting new blocks into the pool of `UnstableBlocks` can be relatively
expensive, and it would be useful to track exactly how expensive it is.

feat: track instruction counts of block insertions

---

canister/src/guard.rs
canister/src/heartbeat.rs
canister/src/lib.rs
e2e-tests/profiling/scenario-1.txt
e2e-tests/profiling/scenario-2.txt

If for any reason the logic in fetching blocks panics, we'll forever stop fetching new blocks.
Use the guard pattern, which guarantees that we always set the `is_fetching_blocks` flag to `false` and continue fetching new blocks whenever we receive a response, even if it traps.

feat: use the guard pattern when fetching blocks.

---

benchmarks/drun.txt
benchmarks/run.sh

In a previous commit, a benchmarks canister was introduced to help benchmark specific parts of the code.
This commit includes a script to run these benchmarks. The script relies on `drun`, which is configured to run benchmarks with practically no instruction limit. For now, it is assumed to be available in the caller's path.
Running `./benchmarks/run.sh`, returns the following:
```
(113_061_801_763 : nat64)
```
In other words, the one benchmark we currently have takes 113B instructions to run (!!)

feat: [EXC-1374] add script for running benchmarks.

---

canister/src/unstable_blocks.rs

Remove todos from the code that we won't be doing, primarily because we don't need to do custom time-slicing on this method.

chore: remove dangling todos

---

canister/src/api/metrics.rs
canister/src/lib.rs

There is now logic in the canister to disable its API automatically if it's not synced with the network, but we have no way of tracking whether or not our definition of "synced" is too sensitive, and whether or not we're frequently flapping between the synced and not synced states.
Add a `is_synced` metric to the canister that we can use to monitor changes in the synced state.

feat: add metric to track if the canister is synced

---

canister/src/metrics.rs
canister/src/state.rs
canister/src/unstable_blocks.rs
dfx.json
e2e-tests/upgradability.sh

There is an "upgradability" test that checks if the canister can be upgraded from the latest release to the current commit successfully. This test is broken due to a typo in the canister's name, resulting in a failed upgrade this week.
Fix the typo in the test, and add a check to ensure that, if a typo were to reintroduced, that the test would fail.

fix: broken upgradability test

---

Cargo.lock
benchmarks/Cargo.toml
benchmarks/src/main.rs
bootstrap/main-state-builder/src/main.rs
bootstrap/state-builder/src/build_address_utxos.rs
bootstrap/state-builder/src/build_balances.rs
bootstrap/state-builder/src/build_utxos.rs
bootstrap/state-builder/src/main.rs
canister/src/address_utxoset.rs
canister/src/api/fee_percentiles.rs
canister/src/api/get_balance.rs
canister/src/api/get_utxos.rs
canister/src/api/send_transaction.rs
canister/src/api/set_config.rs
canister/src/blocktree.rs
canister/src/heartbeat.rs
canister/src/lib.rs
canister/src/main.rs
canister/src/state.rs
canister/src/test_utils.rs
canister/src/tests.rs
canister/src/tests/confirmation_counts.rs
canister/src/types.rs
canister/src/unstable_blocks.rs
canister/src/unstable_blocks/outpoints_cache.rs
canister/src/utxo_set.rs
canister/src/validation.rs
interface/src/lib.rs

* Removes types in `canister/src/types.rs` that are already present in `ic_btc_interface`.
* Merges the `Network` and `NetworkSnakeCase` enums, as keeping both of them is redundant.

refactor: clean up interface types.

---

Cargo.lock
ic-http/example_canister/src/canister_backend/Cargo.toml
ic-http/example_canister/src/canister_backend/canister_backend.did
ic-http/example_canister/src/canister_backend/src/main.rs
ic-http/src/lib.rs
ic-http/src/mock.rs
ic-http/src/request.rs
ic-http/src/storage.rs
ic-http/src/transform.rs
ic-http/tests/api.rs

This PR fixes storing transform functions in a thread-local storage which was preventing to test concurrent http requests.
Previously it was incorrectly calculating the name of the function, since it was called inside `create_transform_context` function with a specific type of `TransformFn`, which loses the name of the function (in contrast to a template parameter) and only stores the function signature (which is always the same).
To fix this it had to convert `create_transform_context` to a template and store a boxed function pointer in a thread-local storage. Added tests to make sure function names are stored properly now.

fix: fix mocking concurrent http requests with transform functions in ic-http

---

ic-http/src/mock.rs
ic-http/src/transform.rs

This PR improves storing mocked response to be either result or an error.
This is a follow-up PR to address code review comments from #183.

chore: refactoring storing mocked responses for ic-http

---

.github/workflows/workflow.yml
watchdog/candid.did
watchdog/src/config.rs
watchdog/src/endpoints.rs
watchdog/src/health.rs
watchdog/src/lib.rs
watchdog/src/storage.rs
watchdog/tests/get_config.sh
watchdog/tests/health_status.sh

This PR adds the option to read a watchdog canister's configuration.
Adds a `get_config` endpoint and corresponding bash-tests.

feat: add watchdog canister config

---

.github/workflows/workflow.yml
Cargo.lock
watchdog/Cargo.toml
watchdog/candid.did
watchdog/src/health.rs
watchdog/src/lib.rs
watchdog/src/metrics.rs
watchdog/src/types.rs
watchdog/tests/metrics.sh

This PR adds Prometheus metrics to a watchdog canister.
Metrics response example:
```
bitcoin_canister_height 786116 1681915083861
explorers_number 6 1681915083861
target_height 786116 1681915083861
height_diff 0 1681915083861
status{height="not_enough_data"} 0 1681915083861
status{height="ok"} 1 1681915083861
status{height="ahead"} 0 1681915083861
status{height="behind"} 0 1681915083861
```

feat: add metrics to watchdog canister

---

watchdog/candid.did
watchdog/src/bitcoin_block_apis.rs
watchdog/src/fetch.rs
watchdog/src/health.rs
watchdog/src/metrics.rs
watchdog/tests/health_status.sh

This PR renames and restructures watchdog canister metrics and health status report.
Watchdog canister is currently tracking only the block height of a Bitcoin canister, but in the future it may also track other endpoints like getting balances, etc. That's why current PR clarifies that the current health status and metrics provide a height related information.
New health report and metrics look the following:
- Main information about the height
- `bitcoin_canister_height`, main chain height of the Bitcoin canister
- `height_target`, derived from explorer heights
- `height_diff`, difference between Bitcoin canister height and target height
- `height_status`, Bitcoin canister height status
- Auxiliary information about the height
- height from each specific explorer
Metrics example:
``` …
```

chore: restructure metrics for watchdog canister

---

watchdog/src/bitcoin_block_apis.rs
watchdog/src/endpoints.rs
watchdog/src/fetch.rs
watchdog/src/lib.rs
watchdog/src/test_utils.rs

This PR removes `api.bitaps.com` block info API provider because of an invalid block height.
A recent measurement revealed a data discrepancy, `api_bitaps_com` explorer height was way behind comparing to others (`358676` vs `786248`). Therefore removing this API provider as invalid.
```
explorer_height{explorer="api_bitaps_com"} 358676 1681989756988
explorer_height{explorer="api_blockchair_com"} 786248 1681989756988
explorer_height{explorer="api_blockcypher_com"} 786248 1681989756988
explorer_height{explorer="blockchain_info"} 786248 1681989756988
explorer_height{explorer="blockstream_info"} 786248 1681989756988
explorer_height{explorer="chain_api_btc_com"} 786248 1681989756988
```

chore: remove api.bitaps.com provider from watchdog canister

---

canister/src/api/get_utxos.rs

There were a number of discussions where we weren't very sure how the system behaves at min_confirmations = 0, so this test serves as documentation.

test: add test to document behaviour at min_confirmations = 0.

---

watchdog/src/bitcoin_block_apis.rs
watchdog/src/endpoints.rs
watchdog/src/test_utils.rs

This PR adds a test case when API provider responds with a text string instead of a valid JSON.

chore: add tests for explorer api abuse to watchdog canister

---

Cargo.lock
ic-http/Cargo.toml
ic-http/example_canister/src/canister_backend/Cargo.toml
ic-http/src/http_request.rs
ic-http/src/lib.rs
watchdog/Cargo.toml
watchdog/src/bitcoin_block_apis.rs

Attach zero cycles to `http_request` in order not to run out of cycles when running on a system subnet.

fix: watchdog canister running out of cycles when sending http_request

---

interface/src/lib.rs

Adding serialize allows us dapps like the NNS dapp to display a SetConfigRequest in JSON

chore: derive Serialize for SetConfigRequest

---

.github/workflows/workflow.yml

This change adds watchdog related jobs into `check-pass` CI job, also restructures it as a list for a better readability.

chore: add watchdog jobs to checks-pass workflow

---

Cargo.lock
watchdog/Cargo.toml
watchdog/candid.did
watchdog/src/api_access.rs
watchdog/src/config.rs
watchdog/src/endpoints.rs
watchdog/src/health.rs
watchdog/src/lib.rs
watchdog/src/metrics.rs
watchdog/src/storage.rs
watchdog/tests/get_config.sh
watchdog/tests/health_status.sh
watchdog/tests/metrics.sh

This change adds reading and writing bitcoin canister API access config flag.
API access target is calculated based on the height health status, actual value is read from the bitcoin canister. If there is a difference between the target and actual values, then watchdog tries to rewrite the bitcoin canister API access config flag.
This change also exposes additional metrics: 
- blocks behind/ahead thresholds
- minimum and actual number of explorers
- API access target

feat: add watchdog stop-switch for bitcoin canister

---

.github/workflows/workflow.yml
.gitignore
Dockerfile
dfx.json
e2e-tests/reproducibility.sh
watchdog/Cargo.toml

This PR adds a watchdog canister to a docker file to build and verify its integrity.
Additionally:
- added reproducibility CI check, which runs docker build 2 times and compares the check sums
- added top-level comment to Dockerfile
- minimised the number of layers by combining commands in a single `RUN` with `&&`
- added packet manager cache cleanup to reduce the image size

chore: add watchdog-canister to docker

---

canister/candid.did
canister/src/api/set_config.rs
interface/src/lib.rs

This PR adds the ability to set a watchdog canister principal in a bitcoin canister config via `set_config` API, which is used to update the bitcoin canister config via proposals.
The watchdog_canister principal ID can be flexibly configured according to your needs. You can either assign an actual principal ID or reset it back to None, providing more control and customization for your canister settings.

chore: add watchdog_canister to set_config_request api

---

interface/src/lib.rs

This PR enabled debug formatter for `Config` structure.
Users of bitcoin-canister may use default formatter "{:?}" for debugging or logging `Config` values.

chore: enable debug formatter for Config

---

.github/workflows/workflow.yml
dfx.json
e2e-tests/upgradability.sh
watchdog/e2e-tests/upgradability.sh

This PR adds an upgradability test for watchdog canister (WDC), similar to the one bitcoin canister has.
Added WDC upgradability test to the github CI.
Both upgradability tests (for watchdog and bitcoin canisters) are made to be similar with improved readability:
- added top-level summary comment
- some comments were rewritten for readability
- fetching and downloading operations were modularised into separate functions

chore: add WDC upgradability test and refactor similar bitcoin-canister upgradability test

---

dfx.json

Adds the internal testnet as a network so that we can easily deploy to it as part of the release process.

chore: add testnet to dfx config

---

Cargo.lock
canister/src/api/get_utxos.rs
canister/src/tests.rs
canister/src/types.rs
interface/Cargo.toml
interface/src/lib.rs
interface/tests/tests.rs

This change improves the type safety of the Bitcoin interface by introducing a newtype for Bitcoin transaction identifiers.

refactor: introduce Txid type

---

canister/src/api/metrics.rs
watchdog/src/metrics.rs

This PR changes the `api_access` metric to an enum with clear `enabled` and `disabled` states for both Bitcoin and watchdog canisters.
Previously, we used `0/1` to represent `disabled/enabled`, but Grafana views no value as zero, causing confusion on charts.
Now, with enums, dashboards will clearly show `enabled` or `disabled`, and won't assume a state if there's no value. 
This is a "nice to have" improvement.

fix: make api_access metric an enum

---

validation/src/header.rs

This PR fixes finding the next difficulty in chain for testnets when verifying headers.
Previous implementation was jumping over one block hash because it was advancing the current header and then was saving its previous block hash (which turned to be a prev-prev hash, one-off bug).
Instead it should have saved the previous block hash first (to avoid its calculation on every iteration) and only then advancing the current header. Or another option for readability to recalculate hash after advancing to the previous header.
Previous implementation:
```rust
while current_hash != initial_header_hash {
// It does not check initial header for PoW.
if is_pow_found {
return current_header.bits;
}
// Advance current header.
current_header = store
.get_with_block_hash(&current_header.prev_blockhash) …
```

fix: fix finding next difficulty in chain for testnets

---

Cargo.lock
benchmarks/Cargo.toml
bootstrap/uploader/Cargo.toml
canister/Cargo.toml
e2e-tests/disable-api-if-not-fully-synced-flag/Cargo.toml
e2e-tests/scenario-1/Cargo.toml
e2e-tests/scenario-2/Cargo.toml
e2e-tests/scenario-3/Cargo.toml
ic-http/Cargo.toml
ic-http/example_canister/src/canister_backend/Cargo.toml
interface/Cargo.toml
watchdog/Cargo.toml

This PR downgrades versions for `candid`, `ic-cdk` and `ic-cdk-macros` revering #213.
The reason is that `candid = "0.9.0-beta.3"` blocks using updated crates `ic-btc-interface`, `ic-btc-validate` in the IC repo due to some candid incompatibility.

chore: downgrade candid from 0.9.0-beta.3 to 0.8.1

---

.gitattributes
.github/workflows/workflow.yml
Cargo.lock
validation/Cargo.toml
validation/src/header.rs
validation/tests/data/block_headers_mainnet.csv
validation/tests/data/block_headers_testnet.csv

The `get_next_target` doesn't have good test coverage, yet it's important and a bug in it can bring the bitcoin integration to a halt or, in a worse case, provide a window for an attacker to feed bad blocks into the system.
This PR adds proptests to add more test coverage to this code.

test: add proptests for computing next header target.

---

Cargo.lock
Cargo.toml
bootstrap/main-state-builder/Cargo.toml
bootstrap/state-builder/Cargo.toml
canister/Cargo.toml
ic-http/Cargo.toml
ic-http/example_canister/src/canister_backend/Cargo.toml
interface/Cargo.toml
validation/Cargo.toml
watchdog/Cargo.toml

This PR moves crate revisions on workspace level and updates them:
- `ciborium` from rev `e719537` from [23 Feb 2023](https://github.com/enarx/ciborium/commit/e719537c99b564c3674a56defe53713c702c6f46) to version `0.2.1` from [7 May 2023](https://github.com/enarx/ciborium/commit/7d8f6e499db51fe52f5d3c2ce1d0e0be61c7eaa2)
- `futures` from `0.3.27` to `0.3.28`
- `serde` from `1.0.132` to `1.0.171`
- `tokio` from `1.15.0` to `1.29.1`

chore: update some crate revisions

---

Cargo.lock
Cargo.toml
ic-http/example_canister/src/canister_backend/Cargo.toml
ic-http/example_canister/src/canister_backend/src/main.rs
ic-http/src/http_request.rs
ic-http/src/lib.rs
ic-http/src/request.rs
ic-http/src/transform.rs
ic-http/tests/api.rs
watchdog/src/bitcoin_block_apis.rs
watchdog/src/endpoints.rs
watchdog/src/http.rs

This PR bumps up `candid` version to `0.9.1`.
Additionally it updates `ic-cdk` to `0.10.0` and `ic-cdk-macros` to `0.7.0`.
Changes:
- removed unsupported `http_request_with_cycles`
- `http_request` now accepts cycles, which should be zero for watchdog canister
- registering transform function does not rely on `std::any::type_name::<F>()` for figuring out function name any more, so it has to be provided manually

chore: bump up candid to 0.9.1

---

interface/src/lib.rs

Currently, there is no way to access the 32 bytes of a transaction ID directly (you can only get a `&[u8]` reference).
This PR adds the implementation of the `From` trait to access the transaction ID bytes.

chore: Implement the `From` trait to access the `Txid` bytes

---

Cargo.lock
interface/Cargo.toml
interface/README.md

There is more than one consumer of `ic-btc-interface`. Having it versioned and published on crates.io would make it more convenient to pull this dependency.

chore: add metadata to publish the ic-btc-interface crate

---

canister/src/heartbeat.rs
canister/src/state.rs
canister/src/types.rs

We've run into a situation where the Bitcoin testnet canister stopped syncing, but there are no logs or information for us to understand what exactly is happening.
This commit adds additional logs to give us this additional visibility in order to triage issues.

chore: add additional logs to the canister heartbeat

---

benchmarks/drun.txt
benchmarks/src/main.rs
canister/src/heartbeat.rs
canister/src/state.rs

Inserting block headers can be deceivingly expensive, as it involves validating the block header, and that can involve the expensive computation of many block hashes.
This commit adds a benchmark to ensure we don't introduce new regressions to this code path.

perf: add benchmark for inserting block headers

---

canister/src/api/metrics.rs
canister/src/blocktree.rs
canister/src/test_utils.rs
canister/src/unstable_blocks.rs

In production, we set a `stability_threshold` of ~144. However, when
we consider the stability of the chain, we consider it weighted by the
blocks' difficulties. This isn't a problem in the normal case, where
block difficulties are very similar.
There are scenarios specific to the Bitcoin testnet, however, that can
make this logic problematic. The difficulty in the Bitcoin testnet can
be reset to the minimum in case a block hasn't been found for 20 minutes.
Consider the following scenario:
* Assume a `stability_threshold` of 144.
* The anchor at height `h` has difficulty of 4642.
* The anchor will be marked as stable if the difficulty-based depth of
the successor blocks is `stability_threshold * difficulty(anchor)` = 668,448
* The difficulty is reset to the minimum of 1.
* The canister …

fix: add a bound on the length of the unstable chain in testnet/regtest

---

canister/src/api/fee_percentiles.rs
canister/src/test_utils.rs
e2e-tests/scenario-1/src/main.rs
test-utils/src/lib.rs
types/src/lib.rs

The specification mentions that the fee percentiles are measured in [millisatoshi/vbyte](https://github.com/dfinity/interface-spec/blob/master/spec/index.md#ic-method-bitcoin_get_current_fee_percentiles-ic-bitcoin_get_current_fee_percentiles). 
This PR updates the code in accordance with the specification.

fix: Use vbyte for the computation of a transaction fee

---

.github/workflows/workflow.yml

Problem: The passing of watchdog_upgradability is not checked in check_pass on GitHub CI

fix: Add watchdog_upgradability to check_pass on GitHub CI

---

canister/src/main.rs
e2e-tests/scenario-1.sh

Problem:
Replicated calls to query methods first go through consensus and then are rejected by the Bitcoin canister, hence wasting resources.
Solution:
Add inspect_message endpoint, which will reject all calls to the query endpoints.

perf: Add inspect_message endpoint to Bitcoin canister

---

e2e-tests/scenario-1.sh

The e2e scenario 1 test started failing lately. It appears that the behavior of dfx has changed and the error messages being returned, which we use in the test, have changed. I don't quite understand how the behavior of one particular version of dfx has changed, unless that version has been modified. I'm following up with the SDK team to understand that. In any case, this fixes the failures we're seeing.

fix: failing scenario 1 test

---

Cargo.lock
canister/Cargo.toml
canister/src/blocktree.rs
canister/src/blocktree/serde.rs

We're now running into a situation where the Bitcoin testnet has ~125k unstable blocks due to a difficulty reset.
Recursively deserializing these blocks, which we do in `post_upgrade`, causes a stack overflow.
Rewrite the `BlockTree` deserialization to be iterative rather than recursive. Running a test with the current production state confirms that it fixes that stack overflow issue.

fix: deserialize `BlockTree` iteratively

---

Cargo.lock
Cargo.toml
benchmarks/Cargo.toml
benchmarks/benches.rs
benchmarks/results.yml
benchmarks/run-benchmark.sh
benchmarks/src/main.rs
canister/Cargo.toml

Replaces `criterion` with our own custom logic for reporting benchmarks. Our own benchmarking reporting offers a number of advantages over `criterion`:
* A simple file for persisting benchmark results across commits.
* The ability to track multiple measurements (e.g. instruction counts and memory)
* An option to persist the results at your leisure (criterion always persists)

feat: improve benchmarking reports

---

development-guide.md

Github doesn't have a good flow for handling releases for two different artifacts. For example, we cannot have a release marked as the latest release for the Bitcoin canister and a different release marked as the latest release for the watchdog canister.
Instead, we now always release the Bitcoin canister and watchdog canister together, and they'll all need to be re-deployed in the case of a new release.
If there happens to be only modifications in one of the binaries, say, the watchdog canister, then in theory the Wasm for the Bitcoin canister would be unchanged, and would therefore not need a release.

docs: Update development-guide.md

---

.github/workflows/workflow.yml

This PR enables `watchdog_health_status` test on CI, the test was fixed in previous PR.

chore: enable watchdog_health_status test on CI

---

Cargo.lock
dfx.json
scripts/build-canister.sh
watchdog/Cargo.toml
watchdog/candid.did
watchdog/e2e-tests/health_status.sh
watchdog/e2e-tests/upgradability.sh
watchdog/e2e-tests/utils.sh
watchdog/src/config.rs
watchdog/src/fetch.rs
watchdog/src/lib.rs

Sets the threshold for blocks ahead/behind from +/- 2 to +/- 100 for bitcoin testnet given that bitcoin testnet often has surges in blocks when the difficulty is low.
The configs of the watchdog canister were not being maintained in this repo, and instead were only maintained in the NNS proposals. After a discussion with @maksymar, we agreed to maintain the configurations here instead to make them easier to review and track.
As a result, the watchdog canister has now been updated to require a bitcoin network when being initialized, and based on that network it'll use the hard-coded bitcoin mainnet/testnet config.

fix: make the bitcoin testnet watchdog less sensitive

---

.github/workflows/workflow.yml
Dockerfile
dfx.json
rust-toolchain.toml

This PR updates dfx version from 0.15.2 to 0.16.0.
This is a preparation to fix IPv4 support for HTTP outcall tests of watchdog canister.

chore: bump dfx from 0.15.2 to 0.16.0

---

.github/workflows/workflow.yml
Cargo.toml
Dockerfile
benchmarks/src/main.rs
canister/src/api/set_config.rs
canister/src/unstable_blocks/next_block_headers.rs
canister/src/utxo_set/utxos.rs
canister/src/utxo_set/utxos_delta.rs
rust-toolchain.toml
watchdog/src/bitcoin_block_apis.rs

Introducing `canbench` requires a newer version of rust, so we first upgrade to the latest version in this commit.

chore: upgrade rust from 1.70 to 1.76

---

.github/workflows/workflow.yml

The way DFX is installed has changed, causing our CI script to fail. This commit updates it to use the official github action to avoid this from happening again in the future.

fix: broken CI on master

---

ic-http/src/lib.rs

This PR fixes `ic-http` doc test by explicitly using `u8` type.

fix: fix ic-http doc test

---

.github/workflows/canbench-post-comment.yml
scripts/canbench_ci_download_artifacts.sh

CI for dependabot PRs like #288 are failing because `canbench` doesn't have the right permissions set up to post a comment with the benchmarking results.
This PR, and a follow-up one, will update CI to fix those permissions as we had done in the `stable-structures` and `canbench` repos.

fix: canbench can run in dependabot PRs (part 1)

---

canister/src/heartbeat.rs
canister/src/tests.rs
canister/src/utxo_set.rs

In an effort to make the FR of the Bitcoin subnet more stable, we reduce the amount of instructions we aim to execute in a single heartbeat execution from 4B instructions to 2B instructions. The hypothesis is that this will lead to a higher and more stable FR overall.

chore: reduce the max instructions of heartbeats from 4B to 2B

---

canister/src/heartbeat.rs
canister/src/state.rs
canister/src/tests.rs
canister/src/utxo_set.rs

Reducing the amount of instructions done per round when ingesting blocks to 1B should result in a smoother finalization rate on the subnet.

chore: reduce block ingestion instruction limit from 2B to 1B

---

.github/workflows/canbench-post-comment.yml

The script used in the workflow file that posts the canbench comment has a typo in it. Unfortunately can't be tested within the same PR, and so these errors aren't always possible to catch in advance.

fix: [EXC-1611] script name in github action

---

Cargo.lock
Cargo.toml
benchmarks/Cargo.toml
benchmarks/src/main.rs
canbench_results.yml
canister/Cargo.toml
canister/src/blocktree/serde.rs
canister/src/lib.rs
canister/src/test_utils.rs
scripts/canbench_ci_run_benchmark.sh
test-utils/Cargo.toml
test-utils/src/lib.rs

Adds a benchmark to measure how much heap memory is being used when upgrading with a large number of unstable blocks. This is the codepath that we'll need to optimize in order to avoid running out of heap memory in the future.

bench: measure memory usage when serializing unstable blocks

---

.dockerignore
.github/workflows/workflow.yml
Cargo.lock
Cargo.toml
Dockerfile
bootstrap/6_compute_canister_state.sh
bootstrap/uploader/Cargo.toml
canister/Cargo.toml
canister/src/main.rs
canister/tests/integration_tests.rs
dfx.json
scripts/build-canister.sh
watchdog/Cargo.toml

Running `pre_upgrade` in the bootstrapping scripts fails with an error that `stable64_size` is only available in canisters.
The bootstrapping scripts do not run the canister code as Wasm, and do not have access to IC-level APIs. Upon further investigation, the reason `stable64_size` was needed was because we were accidentally including `canbench` into the compilation of the canister code - it should only be included when we're benchmarking.
To fix this, the `build-scripts.sh` has been updated to build using `--package` rather than `--bin` - that actually builds the canister from the correct root `Cargo.toml` file and therefore doesn't include any additional features that were required by other packages.
I used this opportunity to add a test using `PocketIC`.

fix: do not include canbench in production

---

Dockerfile

For the upcoming Bitcoin mainnet release, the canister needs to be built with the `legacy_preupgrade` feature, but the docker file doesn't support specifying rust features.
Add a new argument that can be used to specify rust features for the bitcoin canister. It can then be used like this:
```
docker build --build-arg BTC_FEATURES=legacy_preupgrade  -t canisters .
```

feat: allow specifying rust features in docker

---

Cargo.lock
bootstrap/uploader/Cargo.toml
bootstrap/uploader/src/compute_hashes.rs
bootstrap/uploader/src/main.rs

The upload canister compilation was failing with the following error:
```
error: Only features sync,macros,io-util,rt,time are supported on wasm.
--> /Users/ielashi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/lib.rs:467:1
|
467 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
This is due to a dependency on `tokio`, which for some reason `sha256` crate needs. This commit replaces `sha256` with `sha2` which has no such dependencies and fixes the compilation.
It turns out there are not tests to ensure the compilation of the upload canister is correct. These should be added, but better done in a separate PR.

fix: uploader canister compilation

---

watchdog/candid.did
watchdog/src/bitcoin_block_apis.rs
watchdog/src/config.rs
watchdog/src/endpoints.rs
watchdog/src/fetch.rs
watchdog/src/health.rs
watchdog/src/lib.rs
watchdog/src/test_utils.rs

This PR adds `bitcoinexplorer.org` as a Bitcoin mainnet explorer, expanding the total number of data sources to 7.
By increasing the number of explorers, we enhance data diversity and improve overall stability.

chore: add mainnet explorer bitcoinexplorer.org

---

watchdog/src/health.rs

This PR makes calculation of height target for watchdog canister more strict.
- Before: The target height is the median of explorer heights if there are enough explorers (>= `min_explorers`).
- After: The target height is the median only if enough explorers (>= `min_explorers`) are within a defined range of the median.
Configs (currently in prod):
- `mainnet` -- explorers 6, min_explorers 3, blocks range [-2, 2]
- `testnet` -- explorers 3, min_explorers 2, blocks range [-1000, 1000]
Making the height target calculation more strict for the `testnet` is necessary because the `testnet` has fewer explorers and greater instability, leading to large block height divergences. A stricter calculation helps reduce noise and false positives by ensuring only explorers with closely aligned heights are …

feat: improve height target calculation for watchdog canister

---

watchdog/src/config.rs
watchdog/src/fetch.rs

This PR re-enables the `api.bitaps.com` explorer for the testnet.
It was previously disabled due to instability, but with the stricter height target calculation introduced in [PR327](https://github.com/dfinity/bitcoin-canister/pull/327), this should improve the stability of testnet alerts.

feat: re-enable tracking api.bitaps.com testnet explorer in watchdog canister

---

.github/workflows/workflow.yml
Cargo.lock
scripts/build-canister.sh
watchdog/Cargo.toml
watchdog/e2e-tests/watchdog-canister-metadata.sh
watchdog/src/lib.rs

This PR adds metadata to watchdog canister.
Additionally it adds candid compatibility test.

chore: add watchdog canister metadata

---

.gitignore
scripts/build-canister.sh

This updates `gitignore` file for the bootstrap artifacts and paths in `build-canister`.

chore: Update gitignore and minor fixes

---

bootstrap/uploader/src/upload.rs

This PR adds printing progress status and ETA information for uploader canister.
Uploading big canister states can take a lot of time and printing such information is a nice improvement.
```shell
...
Uploading chunk 455/51307 (0.9%), index 38161, ETA: 25h 27m 16s
...
```

feat: add printing progress and ETA for uploader canister

---

validation/src/header.rs

This PR addresses an underflow issue in the calculation of the adjustment interval.
The issue arises because the `time` field in a block header is permitted to have a roughly 3-hour window around the current time (1 hour in the past and 2 hours in the future). This can result in the newest block having a smaller timestamp, especially on testnet networks where many blocks can be created within a short time frame (e.g., over 2'016 blocks in 1 hour).
Reference "MIT Lecture on Bitcoin syncronization" [youtube](https://youtu.be/1Qws70XGSq4?si=oQkIHCk6URu52byz&t=692).

fix: fix header adjustment interval underflow

---

.gitignore
benchmarks/src/main.rs
canister/src/block_header_store.rs
canister/src/heartbeat.rs
canister/src/state.rs
canister/src/test_utils.rs
canister/src/tests.rs
canister/src/types.rs
canister/src/unstable_blocks.rs
canister/src/unstable_blocks/next_block_headers.rs
canister/src/validation.rs
e2e-tests/disable-api-if-not-fully-synced-flag/src/main.rs
test-utils/src/lib.rs
types/src/lib.rs
validation/src/header.rs

This PR renames the usage of `BlockHeader` to `Header` in order to reduce the noise during the `bitcoin` crate update from `0.28.1` to `0.32.4`.
- `0.28.1` https://docs.rs/bitcoin/0.28.1/bitcoin/blockdata/block/struct.BlockHeader.html
- `0.32.4` https://docs.rs/bitcoin/0.32.4/bitcoin/block/struct.Header.html

chore: rename usage of BlockHeader to Header for bitcoin crate v.0.32.4 update

---

.github/workflows/workflow.yml
Cargo.lock
Cargo.toml
canbench_results.yml
scripts/canbench_ci_run_benchmark.sh

This PR upgrades `canbench` crate to v.0.1.8 and `pocket-ic` to 6.0.0.
Canbench tests for this PR showed a regression for `pre_upgrade_with_many_unstable_blocks`, but that is expected since in `canbench` v.0.1.5 there was a fix for correctly accounting the instructions when writing stable memory ([release](https://github.com/dfinity/canbench/releases/tag/v0.1.5)), which is exactly what is happening in bitcoin canister pre_upgrade.

chore: bump up canbench to 0.1.8

---

benchmarks/src/README.md
canister/Cargo.toml
canister/src/tests.rs

This PR adds instructions for generating `testnet_blocks.txt` hex file.
EXC-1813

chore: add instructions for generating testnet_blocks.txt

---

watchdog/candid.did
watchdog/src/bitcoin_block_apis.rs
watchdog/src/config.rs
watchdog/src/endpoints.rs
watchdog/src/fetch.rs
watchdog/src/lib.rs
watchdog/src/test_utils.rs

This PR updates the watchdog canister to support Testnet4 explorers.
Changes
- Removed all Testnet3 explorers, as they are no longer needed.
- Added support for **Mempool** as the sole Testnet4 explorer.
- Added **Mempool** as a Mainnet explorer as well.
EXC-1813

feat: migrate watchdog canister to Testnet4

---

Cargo.toml

This PR updates the `bitcoin` crate from `0.32.4` to `0.32.5` to be the same as in the IC-repo (for bitcoin adapter).

chore: bump up bitcoin version to 0.32.5

---

INTERFACE_SPECIFICATION.md
README.md

Since the Bitcoin integration API will be removed from the IC interface specification, the specification is migrated to the repository itself.

chore: Adding the interface specification

---

.dockerignore
.github/workflows/workflow.yml
.gitignore
canister/src/heartbeat.rs

This PR replaces full `GetSuccessorsResponse` logs with concise stat details.

fix: reduce Bitcoin canister logs by skipping full GetSuccessorsResponse

---

canister/src/api/metrics.rs
canister/src/heartbeat.rs
canister/src/state.rs
canister/src/utxo_set.rs

This PR updates bitcoin canister metrics to include `get_successor` request / response stats.
New fields were added to the `SyncingState` with `#[serde(default)]` to ensure backward and forward compatibility.

feat: add get_successors request / response metrics for bitcoin canister

---

canister/src/api/metrics.rs
canister/src/heartbeat.rs
canister/src/metrics.rs
canister/src/runtime.rs
canister/src/state.rs
dfx.json

This PR adds a histogram metric for tracking `get_successors` request interval.

feat: add get_successors_request_interval histogram metric

---

canbench_results.yml
canister/src/api/metrics.rs
canister/src/blocktree.rs
canister/src/heartbeat.rs
canister/src/state.rs
canister/src/unstable_blocks.rs

This PR fixes a number of block hashes sent in `get_successors` request and also reducing the cost of exposing metrics.

fix: get_successors request sends unique hashes

---

.github/workflows/canbench-post-comment.yml
watchdog/src/config.rs

This PR fixes `min_explorers=1` for the testnet watchdog canister, as only Mempool is currently used.
It also fixes canbench timestamp.

fix: fix min_explorers number for testnet watchdog canister

---

canister/src/unstable_blocks.rs
scripts/canbench_ci_run_benchmark.sh

This PR fixes a formatting issue in Canbench results where emojis were placed in the middle of the line instead of at the end.
Example of how it looks after the fix:
```
Benchmark: get_metrics
total:
instructions: 405.58 M (regressed by 5042.70%) 🔴
heap_increase: 2 pages (regressed from 0) 🔴
stable_memory_increase: 0 pages (no change)
```

fix: fix canbench results formatting

---

bootstrap/README.md

This PR fixes a typo in init param argument of bitcoin canister which is not optional.
Reference [code](https://github.com/dfinity/bitcoin-canister/blob/ef3015332f2d8e33000787891da951d3404ca7de/canister/candid.did#L129).

chore: fix typo

---

.github/workflows/workflow.yml
bootstrap/README.md
canister/src/lib.rs
canister/src/state.rs
interface/src/lib.rs

This PR adds auto-setup for fees if not explicitly provided during initialisation.
Fees values hardcoded depending on config network (mainnet/testnet) and rely on [docs](https://internetcomputer.org/docs/references/bitcoin-how-it-works#bitcoin-testnet).

feat: add default fees for mainnet/testnet networks

---

canister/src/unstable_blocks.rs

This PR adjusts `TESTNET_UNSTABLE_MAX_DEPTH_DIFFERENCE` to balance memory usage and stability. 
It also updates the test to work with the new limit.

chore: adjust testnet unstable max depth difference

---

canister/src/api/metrics.rs
canister/src/unstable_blocks.rs

This PR introduces adaptive logic to control the growth of the unstable block tree in testnets.
Unlike mainnet (which usually has 1–2 branches), testnets often have tens or hundreds of competing branches. This leads to a much larger unstable block tree—potentially 10–100x bigger than the main chain. Since this tree is stored in heap memory, its size must stay below 2 GiB to keep the canister upgradable. With 1 MiB blocks, this limits the tree to about 2,000 blocks.
Previously, testnet depth was capped by a constant (`TESTNET_UNSTABLE_MAX_DEPTH_DIFFERENCE`). This PR replaces that with an adaptive limit based on the `stability_threshold` and current tree size. The new logic applies backpressure to prevent unbounded growth.

fix: adaptive max depth limit calculation for unstable blocks tree

---

INTERFACE_SPECIFICATION.md

This PR updates interface spec with 'Byte Order' section.
Influenced by this [forum post](https://forum.dfinity.org/t/bitcoin-testnet4-nge/42443/3?u=marc0olo).

doc: add Byte Order section to the interface spec

---

.github/workflows/ci-notify-slack.yml

Fixes a bug in the slack notification workflow causing links to not work as expected because of missing escaping of special characters.

fix: escape PR name in Slack notification messages

---

.github/workflows/workflow.yml
scripts/canbench_ci_run_benchmark.sh

This PR renames references from “main” to a generic “baseline” branch to support custom benchmark baselines.

ci: rename 'main' to 'baseline' to support custom benchmark branches

---

e2e-tests/reproducibility.sh

Previously, the reproducibility check was skipped for the `uploader` and `watchdog` canister because of incorrect naming (example: https://github.com/dfinity/bitcoin-canister/actions/runs/16171179985/job/45644840159?pr=409#step:3:1679). This PR fixes the canister names to make the reproducibility check work again and add a condition so that the reproducibility check fails if canister names are wrong.

ci(reproducibility): fix canister names

---

.github/workflows/ci-notify-slack.yml
deployment/mainnet/bitcoin_canister_upgrade_2025_09_04.md
deployment/mainnet/watchdog_canister_upgrade_2025_09_04.md

These proposals aim to upgrade the Bitcoin and Watchdog canisters to the latest release [2025-07-02](https://github.com/dfinity/bitcoin-canister/releases/tag/release%2F2025-07-02) to incorporate several bug fixes, add metrics for better monitoring, and upgrade dependencies to their latest versions.

chore: proposal to upgrade the bitcoin and watchdog canister

---

ic-http/example_canister/Cargo.toml

Remove workspace declaration at ic-http/example_canister/, because src/canister_backend is already included in top-level workspace.

chore: remove redundant cargo workspace

---

deployment/mainnet/bitcoin_canister_upgrade_2025_10_03.md

Proposal to upgrade the bitcoin canister to [release/2025-10-02](https://github.com/dfinity/bitcoin-canister/releases/tag/release%2F2025-10-02).

chore: proposal to upgrade the Bitcoin canister to release/2025-10-02 
